### ISSUE TITLE
Emotion ReactNative

### ISSUE THREAD

**Issue by phated** [ahrefs/bs-emotion#1]
I'm planning to add support for Emotion's ReactNative API but I have a question: Should the types interop with bs-react-native?  They have their own `Style` type when assigning to the `style` property so I'd have to pull in that project as a dependency.

**Comment by alexfedoseev** [comment]
TBH I have zero experience w/ RN, let's check first if I fully understand the issue.

`css` function from `emotion/native` should spit out `Js.Dict.t` to JS, but `bs-react-native` requires `style` prop to be of their own type `Style.t`. So current web binding

```reason
[@bs.module "emotion"]
external make: Js.Dict.t(string) => string = "css";
let css = declarations => declarations->Declarations.toDict->make;
```

must be updated to cast `Js.Dict.t` to `Style.t`, something like this:

```reason
[@bs.module "emotion/native"]
external make: Js.Dict.t(string) => ReactNative.Style.t = "css";
let css = declarations => declarations->Declarations.toDict->make;
```

And we need that `ReactNative.Style.t` in. Correct?

**Comment by phated** [comment]
@alexfedoseev yep, that sums it up.  I was planning to put the native stuff into a module so that it didn't pollute the top level Emotion stuff.  I feel like it's overkill to pull in bs-react-native just to make the 2 libraries work together - is there a way to avoid that other than having bs-react-native rely on re-css? Maybe some sort of generic type?

**Comment by phated** [comment]
I'm pretty sure this wouldn't work but it would be nice to do something like:
```reason
[@bs.module "emotion/native"]
external make: 'rnStyle. Js.Dict.t(string) => 'rnStyle = "css";
let css = declarations => declarations->Declarations.toDict->make;
```

**Comment by alexfedoseev** [comment]
Hmm that actually might work, this [compiles](https://reasonml.github.io/try?rrjsx=true&reason=C4TwDgpgBMULwCgpQD5QIJNVAQgbgQBsJYAzAO3i1IFdys114A+KAIgEM2HcX2AjNgQQBtAAL8AzgDoAtgHsAJjWLsIC4AEt55APTkOWgG4Q2AXSgQAHsAgAnA4SgBjSZIBcUScDubyAcz4Acg54dldJIQQiEigrMM42AFpmCJSKAiA):

```reason
module Style = {
  type t =
    | A
    | B;

  let toString =
    fun
    | A => "a"
    | B => "b";
};

[@bs.module "emotion/native"] external css: string => 'a = "css";

let x = "a"->css->Style.toString;
```
---
Another option is to turn this repo into mono-repo and release `bs-emotion-native` as a separate package (I'm planning to do this mono-repo thing anyway to add ppx package that adds labels to classes).

I can move properties definitions to `re-css` (`module Css.Properties`) so it's possible to just `include` those in bindings.

Thoughts?
