### ISSUE TITLE
BS6+ support

### ISSUE THREAD

**Issue by ryyppy** [ahrefs/bs-emotion#26]
We are preparing the transition to BS v6 & v7 and wanted to check if this library would be ready for the switch?

If yes, it would be good to have instructions on which released versions are compatible with which BS versions.

See [#3914](https://github.com/BuckleScript/bucklescript/issues/3914)

**Comment by jchavarri** [comment]
@ryyppy thanks for all your work coordinating the v7 release.

We will work on the upgrade of the ppx at some point in the (hopefully close) future. We have many production apps using bs-emotion and its ppx, that we'll have to upgrade to bs v7, and the ppx is a blocker for that.

As a side note, I heard that @anmonteiro was going to show how to upgrade the ppx as part of a stream yesterday but I could not join. Antonio, did you end up working on this ppx, or something else?

**Comment by anmonteiro** [comment]
Yes I did this yesterday, and will open a PR soon. We also recorded the stream so I’ll share the video to a wider audience soon too.
