### ISSUE TITLE
Doesn't seem to work in windows

### ISSUE THREAD

**Issue by bikallem** [ahrefs/bs-emotion#31]
Hi,

I am trying to use ```bs-emotion-ppx``` in windows 10 (x64). However, I am getting the following error.

bs-platform : 7.0.1
bs-emotion-ppx: 1.0.0

```
We've found a bug for you!
  C:\Users\user1\source\repos\ctc-ui\src\Index.re

  External preprocessor does not produce a valid file
Command line: C:\Users\user1\source\repos\ctc-ui\node_modules\@ahrefs\bs-emotion-ppx\bin\bs-emotion-ppx.exe "C:\Users\user1\AppData\Local\Temp\1\camlppxa1d8c8" "C:\Users\user1\AppData\Local\Temp\1\camlppx98116c"
```

Any pointers ?

**Comment by jchavarri** [comment]
hey @bikallem thanks for reporting this.

We found out a few days ago about this issue, and we did some exploration to try to isolate the problem: https://github.com/jchavarri/bug-ppx-windows

We don't have windows machines at hand, and we could not replicate the problem in a virtual box, so as far as we could tell it was only happening in CI. Glad you confirmed that is not the case. In case you make any further findings, please share.

I think we will solve this issue by migrating the ppx publishing pipeline to GH actions, like graphql_ppx does, which seems to solve the problem. We have a reference setup available in sample repo [hello-ppx-esy](https://github.com/jchavarri/hello-ppx-esy), but I can't say when we will have the time to apply it to Emotion. Contributions are welcome.

Another approach that doesn't involve changing the publishing pipeline is to use `esy` and consume the ppx from source, by building it locally. There is an example of such approach in the repo, see https://github.com/ahrefs/bs-emotion/tree/master/bs-emotion-ppx/test. In particular this line in bsconfig:

https://github.com/ahrefs/bs-emotion/blob/dfa2dc47c8ca2d22dc5129d56e243b08980091cc/bs-emotion-ppx/test/bsconfig.json#L4

Hope this helps.

**Comment by bikallem** [comment]
> Another approach that doesn't involve changing the publishing pipeline is to use esy and consume the ppx from source, by building it locally. 

Ah interesting. Is ```esy``` ready to be used in bucklescript projects? This is cool. I will try that. Thanks.

**Comment by jchavarri** [comment]
@bikallem After more thoughts, I'm not sure the repo would be ready to consume with `esy` straight away because of the way `bs-emotion-ppx` is a subfolder in the repo. One could clone this repo and use https://esy.sh/docs/en/linking-workflow.html to point to the `bs-emotion-ppx` folder.

Unrelated question, just curious, which version of Node are you using? I am running a CI build for the Windows ppx in this PR https://github.com/ahrefs/bs-emotion/pull/30 and it seems to pass with Node 12 on windows.

**Comment by jchavarri** [comment]
@bikallem Could you try testing in the same project where bs-emotion is failing for you with `bs-log` ppx please? It uses a very similar publishing set up than bs-emotion-ppx but with vs2017-win2016 instead of windows-2019.

https://github.com/MinimaHQ/bs-log/blob/master/.ci/azure-pipelines.yml#L22

**Comment by alexfedoseev** [comment]
^ Interested in this as well since I didn't find Win machine to test it 😄

**Comment by bikallem** [comment]
@jchavarri, @alexfedoseev Just tried ```bs-log```. I am able to build the project without any errors. However, I am unable to see any logs in my chrome browser window. Is ```bs-log``` supposed to print log statements which is visible via the Console window in chrome dev tools?

**Comment by alexfedoseev** [comment]
@bikallem Yep, it should be visible in browser console. Can you post the command you exec to compile the app with bucklescript & log statements in your code?

**Comment by bikallem** [comment]
@jchavarri @alexfedoseev 
I did some investigation. It seems ```esy release``` possibly has some defect on Windows OS. I have created an issue on esy repot - https://github.com/esy/esy/issues/1025. 

In short, until that issue is resolved, we need a way around ```esy release``` functionality to release ```npm package``` which works on windows. Perhaps, in the npm package all we would include would be the binary executables for the linux, macos and windows and in the postinstall script we copy the required binary to ```bin``` folder depending on the OS. @jchavarri what do you think of this approach? 

I am also experimenting with github actions as you suggested and have gone as far as the ```esy release```. WIP here - https://github.com/bikallem/bs-emotion/actions.

@alexfedoseev I believe all ppxes which use ```esy release``` should be affected including ```bs-let```.

**Comment by alexfedoseev** [comment]
@bikallem I suspect that you don’t see log entries in a console b/c you use `log.debug` or `log.info` without proper `BS_LOG` environment variable set. By default, only `log.warn` & `log.error` levels are enabled.

**Comment by bikallem** [comment]
@alexfedoseev oh, I will give that a try.

**Comment by bikallem** [comment]
@alexfedoseev ```bs-log``` is working now. Does ```bs-log``` remove these log statements if the mode is ```production``` by any change?

**Comment by alexfedoseev** [comment]
> Does bs-log remove these log statements if the mode is production?

@bikallem Yes, ppx compiles them to `()` so those don't exist at production runtime.
