### ISSUE TITLE
Cannot read property `toString` of undefined error on yarn install

### ISSUE THREAD

**Issue by peterpme** [ahrefs/bs-emotion#35]
![image (1)](https://user-images.githubusercontent.com/1211905/73077699-486f1280-3e86-11ea-8a6a-dbda040cf48a.png)

Hey, we love this library @draftbit thank you! Sometimes we will get a random error that flexdirection, etc doesn't exist.

It seems like sometimes the minima css library isn't included in the compilation? I have to -make-world -clean-world to get it working

We use create-react-app with Reason

I was hoping somebody else had an idea

Thank you!

**Comment by jchavarri** [comment]
@peterpme Have you maybe been switching branches between BuckleScript versions 7 and 5? One (very random) idea is that after switching branches from 5 to 7, there is some library code js artifacts like minima `re-css` that remains built with v5, while the application code gets built with v7.

I bring this up because `Direction` happens to be an "inner module". And inner modules were compiled as JS arrays in v5, but as objects in v7. This would also explains why a clean build fixes it: the library artifacts get "upgraded" to v7, so inner modules are compiled as objects, and then the consumers can find them.

This would explain the problem, but as I said, it's very random 😄

**Comment by peterpme** [comment]
Hey thanks for the quick response! 

We used to switch between 5 and 7 but no more, everything is on 7 right now. I thought i cleaned out the artifacts but it comes up randomly like you said lol

**Comment by jchavarri** [comment]
Hey @peterpme I thought the problem could probably be related to `bs-emotion` depending on an old version of `re-css`, which depended as well on `bs-platform` v4 (although as `peerDependency` 🤔 ).

I'm not sure if this could be part of the issue, but just published `bs-emotion` and `bs-emotion-ppx` 1.0.1, which point to latest `re-css` (which depends on v7). Worst case, this should remove some warnings 😄 best case, it solves this issue.

Please see if you can upgrade to 1.0.1, and let us know if the problem goes away, thanks!

**Comment by peterpme** [comment]
That's awesome thank you! trying now :)

**Comment by peterpme** [comment]
Hey @jchavarri I'm still having the issue. Here's a breakdown:

- emotion 9.2.12
- ahrefs/bs-emotion 1.0.1
- ahfrefs/bs-emotion-ppx 1.0.1

npm ls includes the following:
```
❯ npm ls @ahrefs/bs-emotion
@draftbit/builder@1.34.3 /Users/peter/Projects/draftbit/builder
└── @ahrefs/bs-emotion@1.0.1

❯ npm ls @minima.app/re-css
@draftbit/builder@1.34.3 /Users/peter/Projects/draftbit/builder
└─┬ @ahrefs/bs-emotion@1.0.1
  └── @minima.app/re-css@1.0.1

❯ npm ls emotion
@draftbit/builder@1.34.3 /Users/peter/Projects/draftbit/builder
├─┬ @ahrefs/bs-emotion@1.0.1
│ └── emotion@9.2.12  deduped
└── emotion@9.2.12

❯ npm ls @ahrefs/bs-emotion-ppx
@draftbit/builder@1.34.3 /Users/peter/Projects/draftbit/builder
└── @ahrefs/bs-emotion-ppx@1.0.1
```

**Comment by jchavarri** [comment]
@peterpme it's hard to know what's going on without being able to reproduce. Do you think there could be a way to isolate the problem in a small sample repo that we can access publicly for debugging?

Otherwise, other things that are worth checking could be:

- Run `bsb -version` from your command line, just to make sure there's not a globally installed `bs-platform` that is being used instead of the one in `node_modules/.bin`.
- Check inside the project the `node-modules/re-css/src/Css.bs.js` (or `node-modules/re-css/lib/js/Css.bs.js`) to see what is the actual content of the generated `Css.bs.js` artifact. In particular, the `Direction` module. Just to confirm this hunch that this package might be compiled with a different version of `bs-platform` somehow.

**Comment by peterpme** [comment]
I think I was able to fix this by adding re-css to my project and then forcing the resolution to 1.0.1. I get a warning saying its not the right version but no issues since :smile: 

```json
  "@minima.app/re-css": "1.0.1",
  "resolutions": {
    "@minima.app/re-css": "1.0.1"
  },

```

Either way, here is my steps:
- `bsb -version` fails, not installed globally
- I DON'T have re-css, I only have `@minima.app/re-css`
- there is a css.bs.js file inside `node_modules/@minima.app/re-css/src/Css.bs.js`

I have this in that file

```var Direction = {
  toString: toString$58
};
```

let me know if this is helpful!

**Comment by jchavarri** [comment]
Thanks for the info!

> I get a warning saying its not the right version

This is interesting, what does the warning say exactly? Maybe another package is also depending on `@minima.app/re-css`, but on an earlier version and there are some ["npm doppelgangers"](https://rushjs.io/pages/advanced/npm_doppelgangers/)?

> I think I was able to fix this  by adding re-css to my project and then forcing the resolution to 1.0.1

Curious, do you have a `yarn.lock` or `package-lock.json`? `@minima.app/re-css` should appear there with version 1.0.1 (but maybe it appears more than once, including _another_ version as well).

> I have this in that file

This seems ok... I was expecting there to be st like:

```js
var Direction = /* module */[/* toString */toString];

var Flex = /* module */[/* Direction */Direction];
```

but there seems to be rather:

```js
var Direction = {
  toString: toString
};

var Flex = {
  Direction: Direction
};
```

**Comment by peterpme** [comment]
Hey sorry I was on a trip 😅 

My yarn.lock file only includes these references:

```
"@ahrefs/bs-emotion@1.0.1":
  version "1.0.1"
  resolved "https://registry.yarnpkg.com/@ahrefs/bs-emotion/-/bs-emotion-1.0.1.tgz#8fbca5b5ee14a4db21e965d67a2e4053f6f825ea"
  integrity sha512-oUSKPX/JZ3UDSrdlNj8cesO7yuxwnxS6PvHK3ZA0uI69jkwGJY7ZUDxzYWRg6x/6fZ8qGSSUEoq/moBmwmpjUg==
  dependencies:
    "@minima.app/re-css" "1.0.1"
    emotion "9.2.12"

"@minima.app/re-css@1.0.1":
  version "1.0.1"
  resolved "https://registry.yarnpkg.com/@minima.app/re-css/-/re-css-1.0.1.tgz#605854db397987c9adbdfb991ebe56e9191c2f3d"
  integrity sha512-j0ocaNP4K7/XdSUy7GhH/MTqyq4ZDeCiRXffoUn85fg5V5bwnD57XZzd5miCBEFRxctgNdBdhp2+x3KSbd3uow==
```

Weirdly, I started getting a new error for `LengthPercentage.toString2 is not a function`:

node_modules/@minima.app/re-css/src/Css.bs.js:

```js
var LengthPercentage = {
  operandToString: operandToString$2,
  toString: toString$4,
  toString2: toString2$1,
  toString3: toString3,
  toString4: toString4
};
```

console.logs inside node_modules/@ahfrefs/bs-emotion/src/Emotion.bs.js:

<img width="302" alt="image" src="https://user-images.githubusercontent.com/1211905/73669765-a6ada980-466d-11ea-8c28-a9374e1454f6.png">

<img width="316" alt="image" src="https://user-images.githubusercontent.com/1211905/73669806-b7f6b600-466d-11ea-970e-45c716866fab.png">

**Comment by peterpme** [comment]
It seems like the file is being overwritten somewhere?

**Comment by peterpme** [comment]
this might also have to do with bs-platform@7.1.0

**Comment by jchavarri** [comment]
@peterpme the error `LengthPercentage.toString2 is not a function:` seems to be the same root cause than the previous one: some modules are trying to access exported values in the bsv7 format (i.e. as JavaScript objects properties) while some other modules actually have their generated code exporting their values in the bsv5 format (as JavaScript arrays values).

Could there be any build caching of some sorts enabled in your setup?

Maybe another check worth doing is making sure that you don't have two versions of bs-platform in your yarn.lock, or anywhere in your project. There really seems to be 2 `bsb` binaries running: one (in v5) that generates the code for `@minima.app/re-css`, so exported values are arrays. Another one in v7 for the main app that consumes that module, and expects the exported values to be object properties.

**Comment by peterpme** [comment]
@jchavarri

- I have esy set installed globally
- running `bsb` doesn't work (`type -a bsb` returns null)
- I've hardcoded a bunch of dependencies

bsconfig.json looks like this. I don't think anything here sticks out?

```
{
  "name": "@drafbit/builder",
  "reason": { "react-jsx": 3 },
  "bsc-flags": ["-bs-super-errors"],
  "warnings": {
    "number": "-44",
    "error": "+8+26+27"
  },
  "sources": [
    {
      "dir": "src",
      "subdirs": true
    }
  ],
  "package-specs": [
    {
      "module": "es6",
      "in-source": true
    }
  ],
  "suffix": ".bs.js",
  "namespace": true,
  "bs-dependencies": [
    "reason-react",
    "reason-apollo-hooks",
    "reason-apollo",
    "re-classnames",
    "color-re",
    "@ahrefs/bs-emotion",
    "@glennsl/bs-json",
    "bs-fetch",
    "bs-react-tabs",
    "bs-webapi"
  ],
  "ppx-flags": [
    "@baransu/graphql_ppx_re/ppx6",
    "@ahrefs/bs-emotion-ppx/bin/bs-emotion-ppx",
    "@jsiebern/get_in_ppx/ppx6"
  ],
  "refmt": 3,
  "gentypeconfig": {
    "language": "flow",
    "module": "es6",
    "importPath": "relative",
    "reasonReactPath": "reason-react/src/ReasonReact.js",
    "exportInterfaces": false,
    "shims": {
      "Js": "Js",
      "Obj": "Obj",
      "React": "ReactShim",
      "ReactEvent": "ReactEvent",
      "ReasonPervasives": "ReasonPervasives",
      "ReasonReact": "ReactShim"
    },
    "debug": {
      "all": false,
      "basic": false
    }
  }
}
```

**Comment by jchavarri** [comment]
bsconfig looks normal...

> Could it be because we have esy.json / esy.lock?

Don't think so... unless you are installing `bs-platform` from esy, which I doubt 😅 

---

One idea, maybe you could you run these from your project root folder to see if there are multiple bs-platform or bsb binaries inside some of the packages?

```
find . -name bsb.exe
```

```
find . -name bs-platform
```

Also, could you check `yarn.lock` to look for multiple `bs-platform` appearances?

**Comment by peterpme** [comment]
- I have 1 bs-platform in yarn.lock
- I *have* built with esy BEFORE because there was a broken refmt parser, I wonder if this is the issue, even though we don't do this anymore
- i checked `bs-platform` across my WHOLE machine and realized my yarn cache had old versions of bs-platform so I removed that

**Comment by peterpme** [comment]
I'm not sure if this is helpful but after running yarn install I got this:

```
[#########################################---------------------------------------] 44872/87695^R
[4/4] 🔨  Building fresh packages...
[1/15] ⠁ bs-platform




Error: /Users/peter/Projects/draftbit/builder/node_modules/@ahrefs/bs-emotion-ppx: Command failed.
Exit code: 1
Command: node ./postinstall.js
Arguments:
Directory: /Users/peter/Projects/draftbit/builder/node_modules/@ahrefs/bs-emotion-ppx
Output:
Could not create _export folder
error: Error: EEXIST: file already exists, mkdir '/Users/peter/Projects/draftbit/builder/node_modules/@ahrefs/bs-emotion-ppx/3'
    at ProcessTermError.ExtendableBuiltin (/usr/local/Cellar/yarn/1.21.1/libexec/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/usr/local/Cellar/yarn/1.21.1/libexec/lib/cli.js:750:123)
    at new ProcessTermError (/usr/local/Cellar/yarn/1.21.1/libexec/lib/cli.js:790:113)
    at ChildProcess.<anonymous> (/usr/local/Cellar/yarn/1.21.1/libexec/lib/cli.js:25884:17)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Pipe.<anonymous> (net.js:664:12)
```

**Comment by jchavarri** [comment]
@peterpme that error is the same as #37 right?

It seems there is something messing with the `node_modules/bs-emotion` package (maybe the `patch-package` tool you mentioned in #37?) So I published a temporary version of the `bs-emotion-ppx` package that changes the postinstall script so it does nothing if the `_export` folder is already there, to prevent failures when `node postinstall` is called on an already install package: `1.0.2-dev.1`.

You can add that version to your `package.json`, only for `bs-emotion-ppx` package, not need to change `bs-emotion`. Let's see if that fixes the problem mentioned above and helps us understand what's going on.

**Comment by peterpme** [comment]
Hey just closing this one out :)
